name = "tealogger-web"
pages_build_output_dir = "./site"

[[d1_databases]]
binding = "DB" # Should match preview_database_id
database_name = "tealogger"
database_id = "d6aa17c4-4246-4ba8-81f0-9840cb7ecdcd" # wrangler d1 info YOUR_DATABASE_NAME
preview_database_id = "DB" # Required for Pages local development